--------------
-- MY 테이블
--------------

SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_MY_SITE_TEMP ;
SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_MY_TARGET2SITE_CNC_TEMP ;

--------------
-- MN 테이블
--------------

SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_MN_SITE_TEMP ;
SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_MN_TARGET2SITE_CNC_TEMP ;

--------------
-- FY 테이블
--------------

SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_FY_SITE_TEMP ;
SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_FY_TARGET2SITE_CNC_TEMP ;

--------------
-- FN 테이블
--------------

SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_FN_SITE_TEMP ;
SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_FN_TARGET2SITE_CNC_TEMP ;
