--------------
-- 1. MY 테이블
--------------
TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
WHERE 1=1
AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
AND T.sex_dv_cd = 'MALE'
AND T.true_at_home = 1
;


--------------
-- 1. MN 테이블
--------------
TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_MN_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_MN_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_FITERED_MN_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_FITERED_MN_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
WHERE 1=1
AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
AND T.sex_dv_cd = 'MALE'
AND T.true_at_home = 0
;
--------------
-- 1. FY 테이블
--------------
TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_FY_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_FY_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_FITERED_FY_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_FITERED_FY_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
WHERE 1=1
AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
AND T.sex_dv_cd = 'FEMALE'
AND T.true_at_home = 1
;
--------------
-- 1. FN 테이블
--------------
TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_FN_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_FITERED_FN_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_FITERED_FN_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_FITERED_FN_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
WHERE 1=1
AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
AND T.sex_dv_cd = 'FEMALE'
AND T.true_at_home = 0
;

--------------
-- 1. Site 테이블 * MY
--------------
-- SELECT * FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP;

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MY_SITE_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MY_SITE_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_MY_SITE_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_MY_SITE_TEMP' AS 
SELECT T.site_id
, T.site_nm
, T.catg_lv1
, T.catg_lv2
, T.catg_lv3
, C.count_occur
, C.avg_use_amount
, C.std_use_amount
, C.min_use_amount
, C.max_use_amount
, C.sum_use_amount
FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS T 
JOIN (
	SELECT M.site_id
	, COUNT(C.imsi_no) AS count_occur
	, AVG(C.use_amount) AS avg_use_amount
	, STDDEV(C.use_amount) AS std_use_amount
	, MIN(C.use_amount) AS min_use_amount
	, MAX(C.use_amount) AS max_use_amount
	, SUM(C.use_amount) AS sum_use_amount
	FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS M
	JOIN SBXL2CK.L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP AS C ON C.site_id = M.site_id
	WHERE 1=1
	GROUP BY 1
	HAVING count_occur > 1
) AS C ON C.site_id = T.site_id
WHERE 1=1
;

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MY_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MY_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_MY_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_MY_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_FITERED_MY_TARGET2SITE_CNC_TEMP AS C 
JOIN SBXL2CK.L2CK_HB5EO_MASTER_MY_SITE_TEMP AS S ON S.site_id = C.site_id
WHERE 1=1
;

--------------
-- 1. Site 테이블 * MN
--------------

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MN_SITE_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MN_SITE_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_MN_SITE_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_MN_SITE_TEMP' AS 
SELECT T.site_id
, T.site_nm
, T.catg_lv1
, T.catg_lv2
, T.catg_lv3
, C.count_occur
, C.avg_use_amount
, C.std_use_amount
, C.min_use_amount
, C.max_use_amount
, C.sum_use_amount
FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS T 
JOIN (
	SELECT M.site_id
	, COUNT(C.imsi_no) AS count_occur
	, AVG(C.use_amount) AS avg_use_amount
	, STDDEV(C.use_amount) AS std_use_amount
	, MIN(C.use_amount) AS min_use_amount
	, MAX(C.use_amount) AS max_use_amount
	, SUM(C.use_amount) AS sum_use_amount
	FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS M
	JOIN (
		SELECT C.*
		FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
		JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
		WHERE 1=1
		AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
		AND T.sex_dv_cd = 'MALE'
		AND T.true_at_home = 0
	) AS C ON C.site_id = M.site_id
	WHERE 1=1
	GROUP BY 1
	HAVING count_occur > 1
) AS C ON C.site_id = T.site_id
WHERE 1=1
;

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MN_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_MN_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_MN_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_MN_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_FITERED_MN_TARGET2SITE_CNC_TEMP AS C 
JOIN SBXL2CK.L2CK_HB5EO_MASTER_MN_SITE_TEMP AS S ON S.site_id = C.site_id
WHERE 1=1
;

--------------
-- 1. Site 테이블 * FY
--------------

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FY_SITE_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FY_SITE_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_FY_SITE_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_FY_SITE_TEMP' AS 
SELECT T.site_id
, T.site_nm
, T.catg_lv1
, T.catg_lv2
, T.catg_lv3
, C.count_occur
, C.avg_use_amount
, C.std_use_amount
, C.min_use_amount
, C.max_use_amount
, C.sum_use_amount
FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS T 
JOIN (
	SELECT M.site_id
	, COUNT(C.imsi_no) AS count_occur
	, AVG(C.use_amount) AS avg_use_amount
	, STDDEV(C.use_amount) AS std_use_amount
	, MIN(C.use_amount) AS min_use_amount
	, MAX(C.use_amount) AS max_use_amount
	, SUM(C.use_amount) AS sum_use_amount
	FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS M
	JOIN (
		SELECT C.*
		FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
		JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
		WHERE 1=1
		AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
		AND T.sex_dv_cd = 'FEMALE'
		AND T.true_at_home = 1
	) AS C ON C.site_id = M.site_id
	WHERE 1=1
	GROUP BY 1
	HAVING count_occur > 1
) AS C ON C.site_id = T.site_id
WHERE 1=1
;

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FY_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FY_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_FY_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_FY_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_FITERED_FY_TARGET2SITE_CNC_TEMP AS C 
JOIN SBXL2CK.L2CK_HB5EO_MASTER_FY_SITE_TEMP AS S ON S.site_id = C.site_id
WHERE 1=1
;

--------------
-- 1. Site 테이블 * FN
--------------

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FN_SITE_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FN_SITE_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_FN_SITE_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_FN_SITE_TEMP' AS 
SELECT T.site_id
, T.site_nm
, T.catg_lv1
, T.catg_lv2
, T.catg_lv3
, C.count_occur
, C.avg_use_amount
, C.std_use_amount
, C.min_use_amount
, C.max_use_amount
, C.sum_use_amount
FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS T 
JOIN (
	SELECT M.site_id
	, COUNT(C.imsi_no) AS count_occur
	, AVG(C.use_amount) AS avg_use_amount
	, STDDEV(C.use_amount) AS std_use_amount
	, MIN(C.use_amount) AS min_use_amount
	, MAX(C.use_amount) AS max_use_amount
	, SUM(C.use_amount) AS sum_use_amount
	FROM SBXL2CK.L2CK_HB5EO_MASTER_SITE_TEMP AS M
	JOIN (
		SELECT C.*
		FROM SBXL2CK.L2CK_HB5EO_MASTER_TARGET2SITE_CNC_TEMP AS C
		JOIN SBXL2CK.L2CK_HB5EO_MASTER_TARGET_TEMP AS T ON T.imsi_no = C.imsi_no
		WHERE 1=1
		AND T.cust_age_idx = 4 AND T.hse_sgmt_cd = '20201'
		AND T.sex_dv_cd = 'FEMALE'
		AND T.true_at_home = 0
	) AS C ON C.site_id = M.site_id
	WHERE 1=1
	GROUP BY 1
	HAVING count_occur > 1
) AS C ON C.site_id = T.site_id
WHERE 1=1
;

TRUNCATE TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FN_TARGET2SITE_CNC_TEMP;
DROP TABLE IF EXISTS SBXL2CK.L2CK_HB5EO_MASTER_FN_TARGET2SITE_CNC_TEMP;
CREATE TABLE SBXL2CK.L2CK_HB5EO_MASTER_FN_TARGET2SITE_CNC_TEMP 
	STORED AS PARQUET
	LOCATION '/SBX/impala_table/L2/CK/L2CK_HB5EO_MASTER_FN_TARGET2SITE_CNC_TEMP' AS 
SELECT C.*
FROM SBXL2CK.L2CK_HB5EO_FITERED_FN_TARGET2SITE_CNC_TEMP AS C 
JOIN SBXL2CK.L2CK_HB5EO_MASTER_FN_SITE_TEMP AS S ON S.site_id = C.site_id
WHERE 1=1
;
